<?php
/**
 * @file
 * work_samples.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function work_samples_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-work_sample-body'
  $field_instances['node-work_sample-body'] = array(
    'bundle' => 'work_sample',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-work_sample-field_github_link'
  $field_instances['node-work_sample-field_github_link'] = array(
    'bundle' => 'work_sample',
    'default_value' => array(
      0 => array(
        'summary' => '',
        'value' => '<a href="https://github.com/kbulloch/PROJECT">View on Github</a>',
        'format' => 'filtered_html',
      ),
    ),
    'deleted' => 0,
    'description' => 'Link to the github repository for this project.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_github_link',
    'label' => 'Github link',
    'required' => 1,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 1,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-work_sample-field_live_demo_link'
  $field_instances['node-work_sample-field_live_demo_link'] = array(
    'bundle' => 'work_sample',
    'default_value' => array(
      0 => array(
        'summary' => '',
        'value' => '<a href="http://kylebulloch.com/PROJECT">Demo</a>',
        'format' => 'filtered_html',
      ),
    ),
    'deleted' => 0,
    'description' => 'Link to a live demonstration of the project.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_live_demo_link',
    'label' => 'Live demo link',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 1,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-work_sample-field_screenshot'
  $field_instances['node-work_sample-field_screenshot'] = array(
    'bundle' => 'work_sample',
    'deleted' => 0,
    'description' => 'Add a screenshot of the project.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_screenshot',
    'label' => 'Screenshot',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Add a screenshot of the project.');
  t('Body');
  t('Github link');
  t('Link to a live demonstration of the project.');
  t('Link to the github repository for this project.');
  t('Live demo link');
  t('Screenshot');

  return $field_instances;
}
